# Copyright (C) <2024> <Merami>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

presets = {
    "1": {
        "order": [
            "default",
            "upper_right",
            "lower_right",
            "upper_left",
            "lower_left",
            "AU12",
            "AU12+",
            "AU12AU25",
            "AU15",
            "AU17",
            "AU10",
            "AU16",
            "AU25",
            "AU18",
            "AU18+",
            "AU22",
            "AU20",
            "AU32",
            "AU26",
            "AU27",
            "AU26Z",
            "AU1",
            "AU2",
            "AU4",
            "AU1AU2",
            "AU42",
            "AU45",
            "f00",
            "f01",
            "f02",
            "f03",
            "f04",
            "AU17D",
            "AU6",
            "AU9",
            "AU38",
            "AU24",
            "AU31",
            "AU27Z",
            "AU30L",
            "AU30R",
            "AU1AU4",
            "AU2AU4",
            "AU6Z",
            "AU18Z",
            "AU22Z",
            "AU13",
            "AD96L",
            "AD96R",
            "AU5",
            "AU7"
        ],
        "states": {
            "default": True,
            "upper_right": True,
            "lower_right": True,
            "upper_left": True,
            "lower_left": True,
            "AU12": True,
            "AU12+": True,
            "AU12AU25": True,
            "AU15": True,
            "AU17": True,
            "AU10": True,
            "AU16": True,
            "AU25": True,
            "AU18": True,
            "AU18+": True,
            "AU22": True,
            "AU20": True,
            "AU32": True,
            "AU26": True,
            "AU27": True,
            "AU26Z": True,
            "AU1": True,
            "AU2": True,
            "AU4": True,
            "AU1AU2": True,
            "AU42": False,
            "AU45": False,
            "f00": False,
            "f01": False,
            "f02": False,
            "f03": False,
            "f04": False,
            "AU17D": False,
            "AU6": False,
            "AU9": False,
            "AU38": False,
            "AU24": False,
            "AU31": False,
            "AU27Z": False,
            "AU30L": False,
            "AU30R": False,
            "AU1AU4": False,
            "AU2AU4": False,
            "AU6Z": False,
            "AU18Z": False,
            "AU22Z": False,
            "AU13": False,
            "AD96L": False,
            "AD96R": False,
            "AU5": False,
            "AU7": False
        }
    },
    "2": {
        "order": [
            "default",
            "AU4",
            "AU1",
            "AU2",
            "f00",
            "AU45",
            "AU5",
            "AU7",
            "AU6",
            "AU24",
            "AU31",
            "AU20",
            "AU18",
            "AU12",
            "AU15",
            "AU17",
            "AU10",
            "AU32",
            "AU16",
            "AU22",
            "AU25",
            "AU26",
            "AU27",
            "upper_right",
            "lower_right",
            "upper_left",
            "lower_left",
            "AU12+",
            "AU12AU25",
            "AU18+",
            "AU26Z",
            "AU1AU2",
            "AU42",
            "f01",
            "f02",
            "f03",
            "f04",
            "AU17D",
            "AU9",
            "AU38",
            "AU27Z",
            "AU30L",
            "AU30R",
            "AU1AU4",
            "AU2AU4",
            "AU6Z",
            "AU18Z",
            "AU22Z",
            "AU13",
            "AD96L",
            "AD96R"
        ],
        "states": {
            "default": True,
            "AU4": True,
            "AU1": True,
            "AU2": True,
            "f00": True,
            "AU45": True,
            "AU5": True,
            "AU7": True,
            "AU6": True,
            "AU24": True,
            "AU31": True,
            "AU20": True,
            "AU18": True,
            "AU12": True,
            "AU15": True,
            "AU17": True,
            "AU10": True,
            "AU32": True,
            "AU16": True,
            "AU22": True,
            "AU25": True,
            "AU26": True,
            "AU27": True,
            "upper_right": False,
            "lower_right": False,
            "upper_left": False,
            "lower_left": False,
            "AU12+": False,
            "AU12AU25": False,
            "AU18+": False,
            "AU26Z": False,
            "AU1AU2": False,
            "AU42": False,
            "f01": False,
            "f02": False,
            "f03": False,
            "f04": False,
            "AU17D": False,
            "AU9": False,
            "AU38": False,
            "AU27Z": False,
            "AU30L": False,
            "AU30R": False,
            "AU1AU4": False,
            "AU2AU4": False,
            "AU6Z": False,
            "AU18Z": False,
            "AU22Z": False,
            "AU13": False,
            "AD96L": False,
            "AD96R": False
        }
    },
    "3": {
        "order": [
            "default",
            "f00",
            "f01",
            "f02",
            "f03",
            "f04",
            "AU42",
            "AU1",
            "AU2",
            "AU4",
            "AU12",
            "AU15",
            "AU17",
            "AU10",
            "AU17D",
            "AU16",
            "AU6",
            "AU9",
            "AU25",
            "AU22",
            "AU20",
            "AU32",
            "AU24",
            "AU18",
            "AU38",
            "AU31",
            "AU26",
            "AU27",
            "AU26Z",
            "AU27Z",
            "AU30L",
            "AU30R",
            "AU1AU2",
            "AU1AU4",
            "AU2AU4",
            "AU12AU25",
            "AU6Z",
            "AU18Z",
            "AU22Z",
            "AU13",
            "AD96L",
            "AD96R",
            "upper_right",
            "lower_right",
            "upper_left",
            "lower_left",
            "AU12+",
            "AU18+",
            "AU45",
            "AU5",
            "AU7"
        ],
        "states": {
            "default": True,
            "f00": True,
            "f01": True,
            "f02": True,
            "f03": True,
            "f04": True,
            "AU42": True,
            "AU1": True,
            "AU2": True,
            "AU4": True,
            "AU12": True,
            "AU15": True,
            "AU17": True,
            "AU10": True,
            "AU17D": True,
            "AU16": True,
            "AU6": True,
            "AU9": True,
            "AU25": True,
            "AU22": True,
            "AU20": True,
            "AU32": True,
            "AU24": True,
            "AU18": True,
            "AU38": True,
            "AU31": True,
            "AU26": True,
            "AU27": True,
            "AU26Z": True,
            "AU27Z": True,
            "AU30L": True,
            "AU30R": True,
            "AU1AU2": True,
            "AU1AU4": True,
            "AU2AU4": True,
            "AU12AU25": True,
            "AU6Z": True,
            "AU18Z": True,
            "AU22Z": True,
            "AU13": True,
            "AD96L": True,
            "AD96R": True,
            "upper_right": False,
            "lower_right": False,
            "upper_left": False,
            "lower_left": False,
            "AU12+": False,
            "AU18+": False,
            "AU45": False,
            "AU5": False,
            "AU7": False
        }
    }
}