name: Build and Release Blender Addon

on:
  push:
    tags:
      - 'v*.*.*' # 当你推送一个以 'v' 开头，后面跟着点分版本号的 Tag 时触发，例如 v1.0.0, v0.5.2

jobs:
  build_and_release:
    runs-on: ubuntu-latest # 在最新的 Ubuntu 虚拟机上运行此作业

    steps:
    - name: Checkout code # 步骤1: 检出你的代码
      uses: actions/checkout@v4

    - name: Set up Python # 步骤2: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # 根据你的 build_release.py 兼容的 Python 版本选择，通常 3.8+ 都可以

    - name: Run build script # 步骤3: 运行你的构建脚本
      run: python build_release.py

    - name: Get addon name and version # 步骤4: 获取插件名称和版本，用于命名发布资产
      id: get_info # 给这个步骤一个ID，方便后续引用它的输出
      run: |
        # 从 build_release.py 中提取项目名称和版本
        # 这是一个简单的示例，可能需要根据你的 build_release.py 实际生成的文件名进行调整
        # 假设 build_release.py 会生成 L4D2_Character_Tools-vX.Y.Z.zip
        ZIP_FILE=$(ls *.zip | head -n 1) # 找到第一个 .zip 文件
        ADDON_NAME=$(echo $ZIP_FILE | sed -E 's/-(v[0-9]+\.[0-9]+\.[0-9]+)\.zip//')
        ADDON_VERSION=$(echo $ZIP_FILE | sed -E 's/.*(v[0-9]+\.[0-9]+\.[0-9]+)\.zip/\1/')

        echo "addon_name=$ADDON_NAME" >> $GITHUB_OUTPUT
        echo "addon_version=$ADDON_VERSION" >> $GITHUB_OUTPUT
        echo "zip_file=$ZIP_FILE" >> $GITHUB_OUTPUT

    - name: Create GitHub Release # 步骤5: 创建 GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/') # 只有当触发事件是 Tag 时才创建 Release
      with:
        files: ${{ steps.get_info.outputs.zip_file }} # 上传由构建脚本生成的 ZIP 文件
        name: ${{ steps.get_info.outputs.addon_name }} ${{ steps.get_info.outputs.addon_version }} # Release 名称
        tag_name: ${{ github.ref_name }} # Release Tag (例如 v1.0.0)
        body: |
          # Release Notes for ${{ steps.get_info.outputs.addon_name }} ${{ steps.get_info.outputs.addon_version }}

          This is an automated release.
          
          **Changes:**
          (You can manually edit this on GitHub after the release is created, or try to parse your updatelog.txt here.)

          **Installation:**
          1. Download `L4D2_Character_Tools-vX.Y.Z.zip` from the Assets section below.
          2. In Blender, go to `Edit -> Preferences -> Add-ons`.
          3. Click `Install...` and select the downloaded zip file.
          4. Enable the add-on.

          ---
          Full Changelog: [Compare changes on GitHub](https://github.com/${{ github.repository }}/compare/${{ github.ref_name }}...HEAD) (You might need to adjust this link for previous tag)
          # TODO: Add more detailed changelog from updatelog.txt

        draft: false # 是否作为草稿发布
        prerelease: false # 是否作为预发布版本
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub 提供的自动认证 Token
